apiVersion: v1
kind: persistentVolume
metadata:
  name: ebs-static
spec:
  accessMode:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-04c5e170b01dbd4a3
---
apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: ""
  volumeName: ebs-static
  accessMode:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-static-demo
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    purpose: ebs-static-demo
    project: roboshop  
spec:
  type: LoadBalanacer
  selector:
    purpose: ebs-static-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80





  