#env are configuration values passed to container like database url , username, password

apiVersion: v1
kind: Pod
metadata:
  name: environment
  labels:
    purpose: demo
    environment: dev
spec:
  contianers:
  - name: nginx
    image: nginx
    env:
    - name: DB_HOST
      value: postgrey-service
    - name: env
      value: DEV