#lables are key value pairs, that can add to kubernates resourced
#like deployments, pod. labels used as selector to select resources

apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    purpose: demo
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx