#login partician in kubernates cluster 
#that organise and isolate the resources, it allows mutiple teams and environments
#share saem cluster and keeping their resources separate

apiVersion: v1 
kind: Namespace
metadata:
  name: namespace
  labels:
    purpose: demo
    environment: dev