apiVersion: v1 
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: demo
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
      - secretRef:
          name: pod-secret