#Basiclly every container have some memory and CPU, so resources are used to provide memory and CPU for container
#request is  minimum amount of CPU and memory gurantee to contianer
#limit is maximun amount of memory can be allowed to use

apiVersion: v1
kind: Pod
metadata:
  name: resources
  labels:
    purpose: demo
  annotations:
    owner: srinu
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "68Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "150m"